### ISSUE TITLE
Kits edit and map-view

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#127]
`/world-map` is cached for 30s and won't reflect users edit on location, tags, etc... after this time. On kit edit or new, we should take advantage of the client MVC and update those setting on the localmodel while updating the API.

**Comment by dsmrs** [comment]
@pral2a still relevant?

**Comment by dsmrs** [comment]
issue too old, I close it

**Comment by viktorsmari** [comment]
BTW Github also offers some bots who can automatically close old or
inactive issues.
