### ISSUE TITLE
Enchance feedback when kit is not pushiblishing

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#215]
When a kit owner looks at the kit page (or on the kit list in profile) and a kit is registered, but is has no last update or last update is older than 5 min prompt a message telling him to repeat the configuration process in order to fix any firmware or configuration issues on the device.

_We should discuss if we store in backend the time update settings by creating a new field on pg where to push this https://github.com/fablabbcn/smartcitizen-web/blob/656b0dbd244225c26def41846c9417ddcf697c5f/src/app/components/kit/setupModule/setuptool.directive.js#L19 as a JSON blob_

**Comment by dsmrs** [comment]
@pral2a still relevant?
