### ISSUE TITLE
Support html on the measurements view

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#227]
https://github.com/fablabbcn/smartcitizen-web/blob/bb57c68349eb7400d33beb3c0471e6d2ef3708c6/src/app/components/kit/showKit/showKit.html#L128-L130

**Comment by dsmrs** [comment]
@pral2a still relevant ?

**Comment by oscgonfer** [comment]
Close this due to inactivity. Reopen if needed @pral2a
