### ISSUE TITLE
On smaller devices: not all sensors are shown on horizontal scroller

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/smartcitizen-web#255]
They get hidden underneath the left arrow.

On the left side, there are at least 2-3 sensors missing:
![2018-02-13_366x100](https://user-images.githubusercontent.com/1689020/36162259-2f9a8bb0-10e6-11e8-8f56-0a599f9c31f5.png)

**Reproduce:**
Example: viewing a kit which has many sensors, try making the window width smaller:
https://smartcitizen.me/kits/3110

I guess this is a issue of CSS **position** / **overflow** / etc. I already spent 2 hours on this but found nothing.

**Comment by alokpant** [comment]
Menu also gets hidden:

<img width="481" alt="screen shot 2018-05-26 at 21 45 52" src="https://user-images.githubusercontent.com/6135761/40579718-4ce3db34-612e-11e8-9021-5234df27719a.png">

**Comment by alokpant** [comment]
hey @viktorsmari, is this issue still available to be taken? Can I look into it?

**Comment by viktorsmari** [comment]
Hey @alokpant ! 

Yes please! But here are some notes:
We are in the middle of a small re-branding which will be deployed on Thursday. You can see how the front page changes here: http://staging.smartcitizen.me

So if you want to take a look, please **branch** out from this branch https://github.com/fablabbcn/smartcitizen-web/tree/hack-change-colors

Also, one of our developers, @pral2a did a quick hack-fix on the scrollbar the other day, just so no data would be hidden underneath, but instead he had to sacrifice the centering of sensors, so they ar not centered anymore. But you will see if you take a look. Thank you! :smile:

**Comment by alokpant** [comment]
@viktorsmari I will look into it this week.

**Comment by alokpant** [comment]
@viktorsmari I am having problem loading page. It is throwing an error:

```
Module 'angulartics.google.analytics' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

Here is what I did:
1. Fork repository
2. Branch out of hack-change-colors
3. npm install

This should automatically install all angulartics and related dependencies. But I kept seeing the error message. So I manually installed them too:

```bash
npm install angulartics
npm i angular angulartics angulartics-google-analytics
```

No success.

**Comment by alokpant** [comment]
Found the issue. It is because of tracking disabled. I use [Brave](https://brave.com/), it automatically disables all tracking and ads.

This however should work even though tracking is disabled. Few browsers come with options to disable tracking. It looks like a bug. Should I create issue for it?

**Comment by dsmrs** [comment]
@alokpant on localhost, all the scripts are injected separately so I guess that's when **Brave** delete the script line. But then in production, it's bundled so shouldn't be a problem. Also, all the dependencies are still handled by **Bower** and not **npm** (npm is only for the dev tools). 

Could be nice to make a  big refactor, but we also thinking about making a new platform from scratch with a new stack (like react, vue or angular 6). But for that, we want to restart from a good UX/UI. We are looking for inputs so if you have ideas or so I'd love to talk about it by email/skype/...

**Comment by alokpant** [comment]
@dsmrs Just received message when trying to access localhost:8080

```
What happened?
The owner of this website (smartcitizen.me) has banned your access based on your browser's signature (423b86eb7b602d95-ua60).
```
Looks like localhost is directly accessing your API key. Is there a way to setup local development?

<img width="1207" alt="screen shot 2018-05-31 at 20 26 43" src="https://user-images.githubusercontent.com/6135761/40801005-2a6be1cc-6512-11e8-9c83-a8a866d30a3d.png">

**Comment by alokpant** [comment]
Honestly, right now I do have alot of context around to offer ideas around Smartcitizen. I will try to fix some issues and see how I can help.

If refactoring is on the roadmap, then perhaps it would be good to get a designer involved. Then try to create a Design System. This would definitely help to ease all these UI related issues to all developers.

**Comment by alokpant** [comment]
Found a way to issues:
```
gulp server
```
also runs on Brave and other tracking disabled browsers. Also no issue with API.

**Comment by alokpant** [comment]
@viktorsmari I branched out from https://github.com/fablabbcn/smartcitizen-web/tree/hack-change-colors but it is no longer accessible. I have based now to my [PR](https://github.com/fablabbcn/smartcitizen-web/pull/321) to master. Please let me know where to base it.

**Comment by alokpant** [comment]
I have not looked at Menu hidden issue, will create another branch and work on it.

**Comment by viktorsmari** [comment]
Ok @alokpant , in the meantime we had merged it to develop. 
The plan is to merge everything on develop to master next monday and then show the new frontpage we were working on.

Thank you so much for spending time on this!

**Comment by alokpant** [comment]
@viktorsmari I have created another issue to tackle hidden menu.

**Comment by alokpant** [comment]
@viktorsmari is there anything I can update in this branch? There has been no feedback or reviews for PR I posted. PR has been stale for 10 days now. It would be good to either update branch and merge it, or close it. I am good with both.

**Comment by viktorsmari** [comment]
I would like to hear @dsmrs view on this, he is our Angular expert!

**Comment by viktorsmari** [comment]
@alokpant Just a thought, in case we did some kind of rewrite, what is your preferred tech stack? What do you think makes sense, in order to get more contribution from the open source community?

**Comment by alokpant** [comment]
@viktorsmari I am learning Vue at the moment. I would guess tech stack should be based on team strength. Pretty sure alot of people will start contributing to any tech. There are always people looking to contribute to OS.

**Comment by dsmrs** [comment]
I think this issue is more related to the mobile access of the app. I think it's something that has to be taken in count from the beginning, with the actual form of the platform there is too much to do. I agree with @alokpant, it has to be discussed with a designer.

I'll close it for now, while we wait for, maybe, a new platform.
Thanks @alokpant for spending time on this!
