### ISSUE TITLE
Graph in temperatures close or below 0

### ISSUE THREAD

**Issue by tomasdiez** [fablabbcn/smartcitizen-web#270]
### Expected behaviour

Graph showing data below 0 in temperature

### Actual behaviour

When close to 0 degrees or below, it is just flat

![screenshot 2018-02-22 at 5 38 05 pm](https://user-images.githubusercontent.com/1511398/36551311-9a0f696c-17f7-11e8-9bb1-5e8a5486042c.png)

### How to reproduce?
This is a sample kit: http://staging.smartcitizen.me/kits/2440

**Comment by viktorsmari** [comment]
This has something to do with the 'last data received' dropdown not being used - if you select anything from  that dropdown, negative values work.

**Comment by viktorsmari** [comment]
Fixed on the API side!
