### ISSUE TITLE
Tags filter doesn't work properly on the new version

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#273]
## Issues on staging

- [x] Screen doesn't show on the proper location and causes a weird problem on scroll

![screenshot 2018-03-14 17 46 54](https://user-images.githubusercontent.com/74249/37417319-3d9d2d0e-27b0-11e8-8c76-9ae229a92ff1.png)

- [x] Tags labels are too small, check the original

![screenshot 2018-03-14 17 47 37](https://user-images.githubusercontent.com/74249/37417314-3b327128-27b0-11e8-8be4-5dc3904bc746.png)

- [ ] **Tags doesn't show up**

![screenshot 2018-03-14 17 47 53](https://user-images.githubusercontent.com/74249/37417295-2f07a544-27b0-11e8-8f6f-3b6dff004e7e.png)

**Comment by pral2a** [comment]
- [ ]  Tags doesn't show up 

Remains open

**Comment by viktorsmari** [comment]
Works when selecting 2 tags, but not 1 tag.
Also, check when removing only 1 tag

**Comment by viktorsmari** [comment]
We get this error when we use only 1 tag:
`TypeError: Cannot assign to read only property 'tags' of object '#<Object>'`

`$stateParams.tags = [$stateParams.tags];`

https://github.com/fablabbcn/smartcitizen-web/blob/master/src/app/app.route.js#L144
