### ISSUE TITLE
Password reset button not fully visible

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#281]
### Expected behaviour

Button, needs to be fully visible

### Actual behaviour

![screenshot 2018-04-10 12 09 53](https://user-images.githubusercontent.com/74249/38554997-e7034e18-3cc4-11e8-956a-99bf6c4078d1.png)

### How to reproduce?

Open the password reset model on the login modal

**Comment by viktorsmari** [comment]
Fixed in 8fa126217b66e9a2f89d497b08f737f57adc2f79
