### ISSUE TITLE
Footer on reset password view

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#282]
### Expected behaviour

Footer section should be at the bottom

### Actual behaviour

![screenshot 2018-04-10 12 11 48](https://user-images.githubusercontent.com/74249/38555457-67356c28-3cc6-11e8-8c46-480716623be5.png)

### How to reproduce?

Reset your password and follow the reset url on your email

**Comment by viktorsmari** [comment]
Fixed in ebf5c5783fd1c4747708c362f61e21ba3eb2108a
