### ISSUE TITLE
Kit has not published view

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#286]
### Expected behaviour
![screenshot 2018-04-18 11 59 16](https://user-images.githubusercontent.com/74249/38925920-46edfb24-4301-11e8-9328-e07d97223e2d.png)
![screenshot 2018-04-18 11 59 28](https://user-images.githubusercontent.com/74249/38925919-46cdc7b4-4301-11e8-866a-197884f10cde.png)

### Actual behaviour
![screenshot 2018-04-18 11 58 59](https://user-images.githubusercontent.com/74249/38925922-47256302-4301-11e8-8916-d67a2e9c2b8c.png)
![screenshot 2018-04-18 11 59 09](https://user-images.githubusercontent.com/74249/38925921-470a527e-4301-11e8-8afb-d09c19d61832.png)

- [ ] Copy doesn't match
- [x] Sections below data (Kit info and user profile are missing)

### How to reproduce?

Visit a kit that never published before https://smartcitizen.me/kits/4511

### Enhancement

I suggest we find a way to also overlay the map area as when a Kit hasn't published any data we don't show the location on the map. Now it gets confusing since you see nothing on the map.

- [ ] Add overlay on map. Discuss with @pral2a

**Comment by viktorsmari** [comment]
Looks like we are using an undocumented directive, `md-backdrop` maybe we should replace it.
https://github.com/angular/material/issues/795
