### ISSUE TITLE
User login modal buttons style

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#287]
**This issues is a low priority one!**

Let's rework the sign up, log in, password reset buttons so they have more contrast as before. However let's keep them above the modal for UX. Discuss with @pral2a

### Expected behaviour

![screenshot 2018-04-18 12 02 34](https://user-images.githubusercontent.com/74249/38926407-dd159a98-4302-11e8-9e77-fc61b6d42467.png)
![screenshot 2018-04-18 12 02 28](https://user-images.githubusercontent.com/74249/38926408-dd3c4634-4302-11e8-9b76-73e9f18e3a33.png)

### Actual behaviour

![screenshot 2018-04-18 12 02 39](https://user-images.githubusercontent.com/74249/38926417-e2a22bac-4302-11e8-8c64-3923a029ee20.png)
![screenshot 2018-04-18 12 02 24](https://user-images.githubusercontent.com/74249/38926418-e2bd7df8-4302-11e8-96a8-6f9f9360c8a7.png)

### How to reproduce?

Click sign in and log in buttons on the nav bar to trigger the modals

**Comment by dsmrs** [comment]
"fixed" by #342
