### ISSUE TITLE
When zooming on the map in mobile tailing is not always loading / visible

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#288]
### Expected behaviour

Map tailing should render when we zoom in. Now it works fine on load and when opening a URL but not when zooming with two fingers on the map.

![img_1728](https://user-images.githubusercontent.com/74249/39521081-533c7592-4e0d-11e8-981b-d7818ace88ad.PNG)

![img_1729](https://user-images.githubusercontent.com/74249/39521082-5355ebb2-4e0d-11e8-81ab-dfdde5b30cf2.PNG)

![img_1727](https://user-images.githubusercontent.com/74249/39521083-536e14a8-4e0d-11e8-8b3c-6eef4989cffc.PNG)

### Actual behaviour

Map tailing should be always visible

### How to reproduce?

Zoom in with two fingers on top of the map

**Comment by dsmrs** [comment]
quite a lot a thing to do to make it "mobile friendly" close the issue for now ? (Can be reopen later, or create a new milestone/projet)
