### ISSUE TITLE
Search bar issues

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#318]
### Expected behaviour
After `enter` search should show loading bar and display the results
### Actual behaviour
Fails to show result. See video
https://www.dropbox.com/s/lrsv4sog70bkp7f/search_bug.mov?dl=0
### How to reproduce?
Scroll to the bottom of the Kit view, then type a search and click enter

**Comment by pral2a** [comment]
Maybe not related but this just happened

![screenshot 2018-05-31 18 47 01](https://user-images.githubusercontent.com/74249/40795679-16735dc6-6503-11e8-9cb3-448acb04b78a.png)

**Comment by dsmrs** [comment]
do you know how to reproduce it? on the develop branch I don't have any problem

**Comment by pral2a** [comment]
To reproduce the actual issue (not the second comment)
1. Open this url http://staging.smartcitizen.me/kits/1438
2. Scroll down to the bottom fo the kit view AKA footer
3. Then go to the nav bar a write something on the search bar like _barcelona_
4. You will see how the search doesn't work

**Comment by dsmrs** [comment]
fixed by #341
