### ISSUE TITLE
Log in window error messages

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#354]
![screenshot 2018-07-26 11 54 29](https://user-images.githubusercontent.com/74249/43266143-df6bc6f6-90ea-11e8-9561-95e35b869f04.png)

Error message appears twice.

Also discuss with @marcelirodriguez about the style of the "password reset" and the "sign in" options

**Comment by viktorsmari** [comment]
The error msg is now only shown once.

Not closing in case we need to discuss a design for this @marcelirodriguez?
