### ISSUE TITLE
Issue with some old kits historical data

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#356]
Some old kits don't show historical data 

https://smartcitizen.me/kits/251

However the `device/251/readings` request seems to return data

**Comment by dsmrs** [comment]
The error is from the back and that return null values
<img width="479" alt="captura de pantalla 2018-07-30 a las 11 03 16" src="https://user-images.githubusercontent.com/12203221/43387967-34a1eb00-93e8-11e8-95cb-dd53191b2483.png">
