### ISSUE TITLE
Checkboxes color

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#358]
Unify checkboxes and other material elements to match the new color palette

![screenshot 2018-08-14 19 11 04](https://user-images.githubusercontent.com/74249/44106841-ff2e35f4-9ff5-11e8-93ac-c2a7cde842fa.png)

**Comment by dsmrs** [comment]
fixed on that's branch #357 just wait to finish the onboarding to go back to csv to implement the style
