### ISSUE TITLE
Tags view loses background when scrolling down

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-web#364]
### Actual behaviour
Background does not move with text in the tag summary view
### How to reproduce?
Select a tag on the map and scroll down (checked on Firefox and Chrome)

![image](https://user-images.githubusercontent.com/13301321/47661250-f5ca7c00-db98-11e8-8fa1-914026590e78.png)

**Comment by viktorsmari** [comment]
Is this still happening?
