### ISSUE TITLE
UX: Low priority: When clicking a 'NOT CONFIGURED' bubble, go to edit the device 

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/smartcitizen-web#372]
### Expected behaviour
There is a red bubble asking for attention 'NOT CONFIGURED'
When clicking it, it **should** take you to a place where you can actually fix the problem; **device edit**.
![2019-01-21_12-32-23](https://user-images.githubusercontent.com/1689020/51472111-dd719400-1d78-11e9-90f1-cf90b6770cfc.png)

### Actual behaviour
Takes you to the map view for the kit.

### How to reproduce?
https://kits.smartcitizen.me/profile/kits

**Comment by tuengominh** [comment]
We already added the "Edit" button :)
