### ISSUE TITLE
Buttons re-styling

### ISSUE THREAD

**Issue by marcelirodriguez** [fablabbcn/smartcitizen-web#378]
**Layout re-styling:**
![layout](https://user-images.githubusercontent.com/40209195/56672488-d24f3c80-66b6-11e9-83b3-c6a3a4244876.jpg)

**Padding proportions:**
![padding](https://user-images.githubusercontent.com/40209195/56672600-00cd1780-66b7-11e9-8272-7da0d32838f1.jpg)

**Buttons colors:**
- [ ] Grey: #eeeeee > Hover color: #DFDFDF

**Status alert color:**
- [ ] Red: #F43D4D

**Comment by pral2a** [comment]
Somethings are missing, sorry for the lack of detail:

1. Match exactly the buttons style from @marcelirodriguez reference. Including icons and colors:

![56672488-d24f3c80-66b6-11e9-83b3-c6a3a4244876](https://user-images.githubusercontent.com/74249/58107179-9fcb2d80-7be9-11e9-9df7-6c769cf59cd5.jpg)

_Ask him for the required assets_

2. Bring the buttons to the `showKit` view (see red arrows)

![Screenshot 2019-05-21 16 56 37](https://user-images.githubusercontent.com/74249/58107240-b96c7500-7be9-11e9-9ad5-6a2ff95cc88d.png)

**Comment by pral2a** [comment]
If we prefer to bring a ready made icon library to the platform instead of @marcelirodriguez icons I am fine but we need to use it across the whole platform (except for the sensor specific icons)

**Comment by viktorsmari** [comment]
Here is how to change the colors globally, using AngularJS Material:

https://material.angularjs.org/latest/Theming/01_introduction

https://material.angularjs.org/latest/demo/colors

Theme can be changed here:
https://github.com/fablabbcn/smartcitizen-web/blob/0edcb4b24cace7b716037ab91efec6a829f46073/src/app/app.module.js#L25
