### ISSUE TITLE
Allow sign in using email (and username)

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#381]
### Expected behaviour

Support username or email to avoid issues with users forgetting their username

### Actual behaviour

Currently login is only supported using username

### How to reproduce?

![Screenshot 2019-05-13 15 50 56](https://user-images.githubusercontent.com/74249/57626835-0b345000-7597-11e9-8479-228b2e2c9594.png)

**Comment by viktorsmari** [comment]
The API now allows this in commit:
https://github.com/fablabbcn/smartcitizen-api/commit/7c3985573a34084aa5cda18f6316ca36b33b8fe8

The web app now indicates emails are allowed in the form in commit:
6d27133ea1f36dc8537dfbcecc99ec837ab649d6
