### ISSUE TITLE
Profile Kits buttons

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#383]
### Expected behaviour

![Screenshot 2019-05-13 17 06 18](https://user-images.githubusercontent.com/74249/57632276-88fd5900-75a1-11e9-87e0-64629be33789.png)

### Actual behaviour

![Screenshot 2019-05-13 17 06 42](https://user-images.githubusercontent.com/74249/57632284-8f8bd080-75a1-11e9-91ef-808149c2fe76.png)

### How to reproduce?

Visit the profile page while owning some devices. You need to be logged in.

**Comment by viktorsmari** [comment]
Is the problem here only the Delete button or something else?

**Comment by pral2a** [comment]
I also added the download data button and changed the text of the sd card / csv upload

El 13 maig 2019, a les 18:46, Viktor Smári <notifications@github.com> va escriure:
