### ISSUE TITLE
Add kit setup selection modal

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#384]
1. Add new Kit button should trigger modal on **2**

![Screen Shot 2019-05-14 at 15 16 41](https://user-images.githubusercontent.com/74249/57705761-bb23bf00-7664-11e9-9beb-c08de055f6e2.png)

2. Selection button:

- The button for SCK 1.0/1.1 will go to the state the previous button was going on `/kits/new` 
- The button for SCK 2.0/2.1 will go to `start.smartcitizen.me` 

![kit selection](https://user-images.githubusercontent.com/74249/57705764-bced8280-7664-11e9-8ca6-071a3b8a8926.png)

**Comment by pral2a** [comment]
Change SCK 1.1 image

![SCK_1_1](https://user-images.githubusercontent.com/74249/58030421-cff9ca00-7b1e-11e9-99ff-190eb551291d.png)

**Comment by viktorsmari** [comment]
New img added in cf4fb4dd6a24c68c86b7d08177f161e8636df6ad
