### ISSUE TITLE
Metrics icons in dropdown with wrong size

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-web#389]
@viktorsmari 

### Expected behaviour

Normal sized icons on kit selection dropdown, in the time series view of the kit's profile

### Actual behaviour

Icons for metrics are oversized like in the image

![imagen](https://user-images.githubusercontent.com/13301321/58576396-87d85700-8244-11e9-8580-66c50020e40e.png)

### How to reproduce?

Go to https://smartcitizen.me/kits/5565, and select a metric in the dropdown to view. Happens in both Firefox and Chrome.

**Comment by viktorsmari** [comment]
@tuengominh can this be related to the changes you did the other day?

**Comment by tuengominh** [comment]
@viktorsmari I inspected already. From what I see this is not related to the changes I did (I changed the fixed size of class sensor_icon from previously 14px to 22px). These icons Oscar mentioned using another class select_image and <img/> tag. But let me fix this issue, I think they must use <md-icon> and the sensor_icon_selected class.
