### ISSUE TITLE
Kits not showing on the map - broken filters

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-web#407]
### Expected behaviour

All kits should show when exploring the map in smartcitizen.me/kits

### Actual behaviour

The kits (I believe ID > 10000) don't show up when exploring the map when exploring the map if you only visit [the web](http://smartcitizen.me/kits).

<img width="1280" alt="Screen Shot 2019-09-18 at 15 53 35" src="https://user-images.githubusercontent.com/13301321/65160600-ed3b9800-da2d-11e9-9f62-802593c6751c.png">

If you visit a particular device (like [this one](https://smartcitizen.me/kits/10041)) then they appear:

<img width="1280" alt="Screen Shot 2019-09-18 at 15 53 36" src="https://user-images.githubusercontent.com/13301321/65160707-2247ea80-da2e-11e9-9193-f833c4aabfb7.png">

**Comment by viktorsmari** [comment]
@oscgonfer is this still an issue?

I think this is the same issue since the other day, some kind of caching?

Now I can see these devices.
I can also see devices 10.000 and 10.000, they are the ones in La Marina De Port
![2019-09-30_12-58-54](https://user-images.githubusercontent.com/1689020/65873016-48508180-e382-11e9-82ce-ae8703e5ebcd.png)

**Comment by oscgonfer** [comment]
Just checked the latest kits and they show while browsing. I don't know how long they take to appear though, it might be something to check?

**Comment by viktorsmari** [comment]
Here we can see for a new device, that one view has 1 more kits (20) vs (21)

![2019-10-09_09-19-11](https://user-images.githubusercontent.com/1689020/66459736-e4127980-ea75-11e9-9d38-9df85538cd2d.png)
![2019-10-09_09-19-02](https://user-images.githubusercontent.com/1689020/66459737-e4127980-ea75-11e9-8ba0-4029276d6dcd.png)

**Comment by viktorsmari** [comment]
Looking at the developer console, I can see the id of the kit on both pages:
![2019-10-09_09-26-33](https://user-images.githubusercontent.com/1689020/66460311-f214ca00-ea76-11e9-82f0-b72373a1d6a4.png)
![2019-10-09_09-25-44](https://user-images.githubusercontent.com/1689020/66460312-f214ca00-ea76-11e9-8179-18a9a67d0f13.png)

But it is not represented on the map.
Notice also that the nr of the request is 1225 on one page, but 1226 on the other. Could be a clue.

**Comment by pral2a** [comment]
Any news from this?

Can we discard this is an issue between `world_map` and `fresh_world_map`? In other words, this looks like a front-end issue only, right?

We are receiving around 2-3 user complains per week, that's why I'm writing a follow-up

**Comment by viktorsmari** [comment]
I trying to narrow it down, and I think we can discard the `fresh_world_map` - It is not called on either `/kits/` or `/kits/:id`, so looks like we are not using it in this case.

The `/kits/` endpoint already has the missing kits info in the `data` object on map initialize.

https://github.com/fablabbcn/smartcitizen-web/blob/cdc9b3f31fbf08442bcfe6f73bd1fe61b2629cf9/src/app/components/map/map.controller.js#L162-L166

When I console log the `data`, I can see the missing kits, but they are not shown on the map when we visit `/kits/` only on `/kits/:id`
