### ISSUE TITLE
Rate limits impede browsing of the web-app when not logged in or logged in as user without admin/researcher privileges

### ISSUE THREAD

**Issue by timcowlishaw** [fablabbcn/smartcitizen-web#447]
Mentioned on fablabbcn/smartcitizen-api#166 - When i am browsing the webapp while not logged in as a researcher or admin (o sea, logged in as an unprivileged user or not logged in at all), requests to the API periodically return 429 (due to rate limiting) and data on the page is not loaded.

<img width="1796" alt="Screenshot 2023-10-26 at 08 31 02" src="https://github.com/fablabbcn/smartcitizen-api/assets/4279/06c03f82-0411-40de-becc-e51b8bc41f20">

**Comment by pral2a** [comment]
See https://github.com/fablabbcn/smartcitizen-web/issues/443#issuecomment-1781054481 Thanks!

**Comment by oscgonfer** [comment]
https://github.com/fablabbcn/smartcitizen-web/pull/454
