### ISSUE TITLE
Landing: Make contact email visible

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-web#484]
Unfortunately, most people today use web-based email services like Gmail, and the "mailto" links are not properly handled on many computers. To avoid losing potential interested people, I recommend making the info@sc email address visible. It could be placed above or below the button, or even incorporated into the button itself.

![image](https://github.com/user-attachments/assets/4807901c-f4d6-451d-875a-460ca546e38e)

Do you agree?

**Comment by oscgonfer** [comment]
https://github.com/fablabbcn/smartcitizen-web/commit/528ef1b1d6ced0927228e91d60bc812fd73bbb08
